name: LaTeX

on:
  push:
    branches: [main]
    paths:
      - neural-networks/**
      - lane-emden/**
      - einführung/**

jobs:
  build_latex:
    runs-on: ubuntu-24.04

    steps:
      - name: Partial Clone
        shell: bash
        run: |
          REPO="https://${GITHUB_ACTOR}:${{ secrets.GITHUB_TOKEN }}@github.com/${GITHUB_REPOSITORY}.git"
          # git config --global init.defaultBranch main
          git config --global user.email github-actions@github.com
          git config --global user.name github-actions
          git clone -q --filter=blob:none --no-checkout --depth=1  --sparse $REPO .
          git sparse-checkout init --cone
          git sparse-checkout set neural-networks lane-emden einführung
          git checkout

      - uses: addnab/docker-run-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          registry: ghcr.io
          image: ghcr.io/cpp-review-dune/introductory-review/texlive:latest
          options: |
            -v ${{github.workspace}}:/work
          shell: bash
          run: |
            sudo chown -R gitpod:gitpod /work
            sudo pacman -Syu --needed --noconfirm python-matplotlib python-scipy python-sympy
            pushd /work/neural-networks
            arara Sample
            popd
            pushd /work/lane-emden
            arara Sample
            pushd proposal
            arara template
            popd
            pushd poster
            arara main
            popd
            pushd beamer
            arara presentazione
            popd
            # ./figure1.py
            popd
            pushd /work/einführung
            arara main
            popd
            mkdir -p /work/public
            mv /work/lane-emden/**/.pdf /work/public
            # mv /work/quizes/entrance*.pdf /work/public

      - name: "Tar files"
        run: |
          sudo chown runner:docker -R .
          tar --zstd -cf PDF.tar.zst public/*.pdf

      - uses: actions/upload-artifact@v4
        with:
          name: PDF-artifact
          path: PDF.tar.zst
          if-no-files-found: error
          retention-days: 90
